"""Scan repo for SKILL.md files and generate .ai/skills-index.md."""

import os
import re

REPO_ROOT = os.path.dirname(
    os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    )
)
OUTPUT = os.path.join(REPO_ROOT, ".ai", "skills-index.md")
SCAN_DIRS = [
    (".ai/plugins", "Plugins"),
    (".ai/skills", "Skills"),
    (".local/skills", "Personal Skills"),
]


def parse_description(text):
    """Extract description from frontmatter, handling single-line, quoted, and
    YAML folded-scalar (> ) multi-line descriptions."""
    m = re.search(r"^description:\s*>\s*\n((?:\s{2,}.+\n?)*)", text, re.MULTILINE)
    if m:
        # YAML folded scalar: join indented continuation lines with spaces
        lines = [line.strip() for line in m.group(1).split("\n") if line.strip()]
        return " ".join(lines)
    m = re.search(r'^description:\s*["\']?(.+?)["\']?\s*$', text, re.MULTILINE)
    if m:
        return m.group(1).strip()
    return None


def parse_frontmatter(path):
    try:
        with open(path, encoding="utf-8") as f:
            content = f.read()
    except Exception:
        return None
    # Use search (not match) — some files have text before the --- delimiter
    m = re.search(r"^---\n(.*?)\n---", content, re.MULTILINE | re.DOTALL)
    if not m:
        return None
    block = m.group(1)
    name = re.search(r'^name:\s*["\']?(.+?)["\']?\s*$', block, re.MULTILINE)
    desc_text = parse_description(block)
    triggers = []
    t_block = re.search(r"^triggers:\s*\n((?:\s+-.+\n?)*)", block, re.MULTILINE)
    if t_block:
        for line in t_block.group(1).split("\n"):
            t = re.match(r'\s+-\s+["\']?(.+?)["\']?\s*$', line)
            if t:
                triggers.append(t.group(1))
    if name and desc_text:
        return {
            "name": name.group(1).strip(),
            "description": desc_text,
            "triggers": triggers,
        }
    return None


def scan():
    results = {}
    for scan_dir, group_name in SCAN_DIRS:
        full_dir = os.path.join(REPO_ROOT, scan_dir)
        if not os.path.exists(full_dir):
            continue
        for root, dirs, files in os.walk(full_dir):
            if "SKILL.md" in files:
                path = os.path.join(root, "SKILL.md")
                rel = os.path.relpath(os.path.dirname(path), REPO_ROOT).replace(
                    "\\", "/"
                )
                fm = parse_frontmatter(path)
                if fm:
                    results.setdefault(group_name, []).append({**fm, "path": rel})

    # Generate markdown
    total = sum(len(v) for v in results.values())
    lines = [
        "# Skill Index",
        "",
        f"{total} skills available. Auto-generated by `scan.py`. Run to refresh.",
        "",
    ]
    for group_name in [g for _, g in SCAN_DIRS if g in results]:
        skills = results[group_name]
        lines.append(f"## {group_name} ({len(skills)})")
        lines.append("")
        lines.append("| Skill | Path | Triggers | Description |")
        lines.append("|-------|------|----------|-------------|")
        for s in skills:
            trigger_str = (
                ", ".join(f"`{t}`" for t in s["triggers"]) if s["triggers"] else "—"
            )
            lines.append(
                f"| {s['name']} | `{s['path']}/` | {trigger_str} | {s['description']} |"
            )
        lines.append("")

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {total} skills to {OUTPUT}")


if __name__ == "__main__":
    scan()
